name: Daily Electricity Tracker

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  track_usage:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This ensures the runner uses the built-in GITHUB_TOKEN for the push
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tracking script
        run: |
          # You have to activate the venv again in this new step
          source venv/bin/activate
          python3 kasa_logger_1.py
          python3 kasa_logger_2.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add server_power_usage_plug1.csv
          git add server_power_usage_plug2.csv
          git commit -m "Update electricity usage for $(date +'%Y-%m-%d')" || exit 0
          git push
